/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as OrderTrackingRouteImport } from './routes/order-tracking'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PressRouteImport } from './routes/press'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as OrderDetailsIdRouteImport } from './routes/order-details.$id'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTrackingRoute = OrderTrackingRouteImport.update({
  id: '/order-tracking',
  path: '/order-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderDetailsIdRoute = OrderDetailsIdRouteImport.update({
  id: '/order-details/$id',
  path: '/order-details/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/order-tracking': typeof OrderTrackingRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/press': typeof PressRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/size-guide': typeof SizeGuideRoute
  '/support': typeof SupportRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/order-details/$id': typeof OrderDetailsIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/order-tracking': typeof OrderTrackingRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/press': typeof PressRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/size-guide': typeof SizeGuideRoute
  '/support': typeof SupportRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/order-details/$id': typeof OrderDetailsIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collections': typeof CollectionsIndexRoute
  '/journal': typeof JournalIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/lookbook': typeof LookbookRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/order-tracking': typeof OrderTrackingRoute
  '/orders': typeof OrdersRoute
  '/payment': typeof PaymentRoute
  '/press': typeof PressRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/shipping': typeof ShippingRoute
  '/size-guide': typeof SizeGuideRoute
  '/support': typeof SupportRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/collections/$slug': typeof CollectionsSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/order-details/$id': typeof OrderDetailsIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/collections/': typeof CollectionsIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/account'
    | '/admin'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/lookbook'
    | '/order-confirmation'
    | '/order-tracking'
    | '/orders'
    | '/payment'
    | '/press'
    | '/privacy-policy'
    | '/refund-policy'
    | '/register'
    | '/search'
    | '/shipping'
    | '/size-guide'
    | '/support'
    | '/sustainability'
    | '/terms'
    | '/wishlist'
    | '/admin/orders'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/order-details/$id'
    | '/product/$slug'
    | '/collections/'
    | '/journal/'
    | '/admin/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/account'
    | '/admin'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/lookbook'
    | '/order-confirmation'
    | '/order-tracking'
    | '/orders'
    | '/payment'
    | '/press'
    | '/privacy-policy'
    | '/refund-policy'
    | '/register'
    | '/search'
    | '/shipping'
    | '/size-guide'
    | '/support'
    | '/sustainability'
    | '/terms'
    | '/wishlist'
    | '/admin/orders'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/order-details/$id'
    | '/product/$slug'
    | '/collections'
    | '/journal'
    | '/admin/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/account'
    | '/admin'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/lookbook'
    | '/order-confirmation'
    | '/order-tracking'
    | '/orders'
    | '/payment'
    | '/press'
    | '/privacy-policy'
    | '/refund-policy'
    | '/register'
    | '/search'
    | '/shipping'
    | '/size-guide'
    | '/support'
    | '/sustainability'
    | '/terms'
    | '/wishlist'
    | '/admin/orders'
    | '/collections/$slug'
    | '/journal/$slug'
    | '/order-details/$id'
    | '/product/$slug'
    | '/collections/'
    | '/journal/'
    | '/admin/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  LookbookRoute: typeof LookbookRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  OrderTrackingRoute: typeof OrderTrackingRoute
  OrdersRoute: typeof OrdersRoute
  PaymentRoute: typeof PaymentRoute
  PressRoute: typeof PressRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  ShippingRoute: typeof ShippingRoute
  SizeGuideRoute: typeof SizeGuideRoute
  SupportRoute: typeof SupportRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsRoute: typeof TermsRoute
  WishlistRoute: typeof WishlistRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  JournalSlugRoute: typeof JournalSlugRoute
  OrderDetailsIdRoute: typeof OrderDetailsIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-tracking': {
      id: '/order-tracking'
      path: '/order-tracking'
      fullPath: '/order-tracking'
      preLoaderRoute: typeof OrderTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-details/$id': {
      id: '/order-details/$id'
      path: '/order-details/$id'
      fullPath: '/order-details/$id'
      preLoaderRoute: typeof OrderDetailsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
  }
}

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminRouteChildren {
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  LookbookRoute: LookbookRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  OrderTrackingRoute: OrderTrackingRoute,
  OrdersRoute: OrdersRoute,
  PaymentRoute: PaymentRoute,
  PressRoute: PressRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  ShippingRoute: ShippingRoute,
  SizeGuideRoute: SizeGuideRoute,
  SupportRoute: SupportRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsRoute: TermsRoute,
  WishlistRoute: WishlistRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  JournalSlugRoute: JournalSlugRoute,
  OrderDetailsIdRoute: OrderDetailsIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
